### PR TITLE
Fix linkedin api v2 regressions in related to email address

### PR DESCRIPTION
**Pull request by gaurav7h4p4**
The email value became a single-element array after the recent changes. Should be a String.

### CODE REVIEW

**Comment by PoBuchi** [comment]
@gaurav- Yes, I left it as array as Linkedin now returns an array

**Comment by gaurav7h4p4** [comment]
@PoBuchi the schema (although undocumented) for `serviceData` seems to have `email` as a string rather than an array, as is evident from these official implementations:
https://github.com/meteor/meteor/blob/release-1.6.1/packages/google-oauth/google_server.js#L74
https://github.com/meteor/meteor/blob/release-1.6.1/packages/github-oauth/github_server.js#L14

It would be safer to stick with that implicit schema.

**Comment by PoBuchi** [comment]
yeah - true, but all other fields differs in every platform - facebook, google, etc.. And Linkedin API V2 is completely different from first version, like person name is returned in dif format. So everyone needs to update their apps to use new api. But about email, maybe we can do email field `email: linkedinEmails[0]`, and have array of emails in `linkedinEmails` key. For easier use, but I am quite not sure, as there are no unified Meteor fields schema for external services

**Comment by PoBuchi** [comment]
Or maybe add extra option for configuring `fields` so you can ask to get all data in cleaner format, if you don't care about localizations smt like that, or just simple on - off , `cleandUpData: true`
```js
profile: {
   firstName: 'Jon',
   lastName:  'Doe'
   linkedinId: 'id',
   email: 'single@email.com',
   picture: 'singleUrl' // specify wich identifier you want first or last(last one is with highest res)
}
```

**Comment by PoBuchi** [comment]
I have created issue on [accounts-linkedin](https://github.com/PoBuchi/meteor-accounts-linkedin/issues/30) as most of people will look there anyways

**Comment by gaurav7h4p4** [comment]
Unfortunately, there are many undocumented assumptions in Meteor, so leaving `email` as it is is recommended. Any extra fields won't break anything, so 👍 to `linkedinEmails` (perhaps call them `registeredEmails` since `linkedin` is already implied). See the latest changes in the PR

**Comment by PoBuchi** [comment]
Just looked ant github-oauth, they MDG return 2 email fields: email as string, and emails array so let's do like that, 

```js

emails = getEmails()

email: emails[0],
emails
```

**Comment by PoBuchi** [comment]
So can you change to getEmails, and fields to email & emails, and I will merger this bit, and no need to check if email available, as Linkedin user can't be without one

**Comment by gaurav7h4p4** [comment]
Done

**Comment by PoBuchi** [comment]
`fields.emailAddress` I don't think it's needed , as now we normalizing with the rest packages for `email` field. As everyone still will need to review changes as name,  profilePicture fields are different as well

**Comment by gaurav7h4p4** [comment]
That's for backward compatibility of all old users of this package. I'm one of them :) My code relies on that name and it would be good to not have to change those parts of the code.

**Comment by PoBuchi** [comment]
Ok let's leave it for time being

**Pull request merged**
